title: Work Support Operations Trend Analysis
description: Operational Workload Forecast (MA)
author: "Derrick Dzormeku"

theme: jekyll-theme-cayman

baseurl: "/vle-student-success-predictive-analytics"
url: "https://dertornam.github.io"

# Optional plugins (these are safe with Cayman)
plugins:
  - jekyll-paginate
  - jekyll-gist
