title: Work Support Operations Trend Analysis
description: Operational Workload Forecast (MA)
author: "Derrick Dzormeku"

theme: jekyll-theme-cayman

# IMPORTANT: baseurl must match this repository name exactly
# Example repo: https://dertornam.github.io/work-support-ops-trend-analysis
baseurl: "/work-support-ops-trend-analysis"
url: "https://dertornam.github.io"

plugins:
  - jekyll-gist
